# ***Practical Questions:***

###1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [2]:
import numpy as np

array = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns (transpose)
transposed_array = np.transpose(array)

array, transposed_array


(array([[65, 34, 55],
        [34, 31, 33],
        [45, 89,  3]]),
 array([[65, 34, 45],
        [34, 31, 89],
        [55, 33,  3]]))

###2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [3]:
import numpy as np

array_1d = np.arange(10)

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

array_1d, array_2x5, array_5x2


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))

###3.  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [4]:
# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the array, making it a 6x6 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

array_4x4, array_with_border


(array([[0.4418223 , 0.80668937, 0.29765529, 0.32852885],
        [0.53101453, 0.24367814, 0.86607411, 0.48507406],
        [0.68489308, 0.08939538, 0.22218596, 0.11156916],
        [0.74481832, 0.50594494, 0.73376355, 0.48585358]]),
 array([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.4418223 , 0.80668937, 0.29765529, 0.32852885,
         0.        ],
        [0.        , 0.53101453, 0.24367814, 0.86607411, 0.48507406,
         0.        ],
        [0.        , 0.68489308, 0.08939538, 0.22218596, 0.11156916,
         0.        ],
        [0.        , 0.74481832, 0.50594494, 0.73376355, 0.48585358,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]]))

###4.  Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [5]:
import numpy as np

array_step = np.arange(10, 61, 5)

array_step

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

###5.  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [6]:
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
upper_case = np.char.upper(string_array)
lower_case = np.char.lower(string_array)
title_case = np.char.title(string_array)
capitalize_case = np.char.capitalize(string_array)

upper_case, lower_case, title_case, capitalize_case

(array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6'),
 array(['python', 'numpy', 'pandas'], dtype='<U6'),
 array(['Python', 'Numpy', 'Pandas'], dtype='<U6'),
 array(['Python', 'Numpy', 'Pandas'], dtype='<U6'))

###6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [7]:
words_array = np.array(['hello', 'world', 'numpy', 'python'])

spaced_words = np.char.join(' ', words_array)

spaced_words


array(['h e l l o', 'w o r l d', 'n u m p y', 'p y t h o n'], dtype='<U11')

###7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [8]:
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

addition, subtraction, multiplication, division

(array([[ 8, 10, 12],
        [14, 16, 18]]),
 array([[-6, -6, -6],
        [-6, -6, -6]]),
 array([[ 7, 16, 27],
        [40, 55, 72]]),
 array([[0.14285714, 0.25      , 0.33333333],
        [0.4       , 0.45454545, 0.5       ]]))

###8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [9]:
identity_matrix = np.eye(5)

diagonal_elements = np.diag(identity_matrix)

identity_matrix, diagonal_elements


(array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 array([1., 1., 1., 1., 1.]))

###9.  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [10]:
from sympy import isprime

random_integers = np.random.randint(0, 1000, 100)


prime_numbers = [num for num in random_integers if isprime(num)]

random_integers, prime_numbers

(array([680, 491, 343, 370, 595, 984, 583, 594,  50, 773, 511, 667, 435,
        286, 855, 901,  33, 309, 907,   0, 795,  91, 819, 437, 860, 528,
        990, 939, 973, 155, 647, 727, 989, 211, 802,  32, 921, 906, 745,
        394, 331, 852, 190, 419, 211, 959, 338, 419, 658, 269, 499, 476,
         75, 570, 529, 239, 760, 418, 375, 697, 846, 561, 922, 601, 553,
        484, 887, 884, 116, 123, 798, 383, 767, 555, 398, 283, 447, 451,
         53,  74, 193, 477, 333, 753, 606, 468, 679, 373, 155, 846, 611,
         67, 600, 801, 452, 356, 707, 331, 249, 168]),
 [491,
  773,
  907,
  647,
  727,
  211,
  331,
  419,
  211,
  419,
  269,
  499,
  239,
  601,
  887,
  383,
  283,
  53,
  193,
  373,
  67,
  331])

###10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [11]:
daily_temperatures = np.random.randint(15, 35, 30)

weeks = daily_temperatures[:28].reshape(4, 7)

weekly_averages = weeks.mean(axis=1)

daily_temperatures, weekly_averages

(array([25, 21, 22, 20, 16, 31, 18, 31, 17, 17, 33, 30, 28, 22, 26, 30, 24,
        25, 27, 24, 15, 25, 24, 15, 24, 23, 31, 18, 22, 30]),
 array([21.85714286, 25.42857143, 24.42857143, 22.85714286]))