# **Theoretical Assigment :-**

## **Ans 1**

Numpy is fundamental libary for scientific computing and ata analysis in Python.
Puprose and Advantages of Numpy are given below:

# Purpose of Numpy:-

a) **Efficient Numerical Computations**:- It is designed to handle numerical computations.Python lists, especially for large datasets.

b)**Foundation for Other libraries**:- It serves as a crore builing block for other scientific computing libraries like Scipy, pandas and scikit-learn.

c)**Multi-dimensional Arrays:-** Allows easy handle and manipulation of multi-dimensional its is crucial for tasks in data scence, machine learning and simulations.

# Advantages of Numpy:-

a)**Performance and Speed:-** NUmpy operations are perform in lower level using C and Fortran libraries, making them as much as fast compared to Python's list operations, especially large datasets.

b)**Memory Efficiency:-** Numpy consume lesss memory than equivalent Python Lists, as they are stored in blocks of memory faster access and manipulation.

c)**Broadcasting:-** Supports broadcasting it allows to perform operations on arrays of different shapewithout loops, code and reduce computation time.

d)**Vectorization:-** Many Operations Numpy includes  mathematical functions such as linear algebra, statisical operations, random number makes it comprehensive too for scientific computing.

e)**Extensive Functionality:-** Numpy includes numerous mathematical functions, for eg: linear algebra, random number generations, make it comprehensive tool for scientific computing.

# NumPy Enhances Python's Capabilities:-

a)**Integration with other Languages:-**  NumPy can easily share with libaries written in C, C++, use of efficient low level implementations with Python Programs.

b)**Efficient Data Structures:-**  Introduces the ndarray, efficient multi-dim array object is much faster than Python's built in lists.

c)**Simplifies Complex Operations:-** Operations like matrix multiplication, statistical analysis become straightward and efficient with NumPy.

d)**Mathematical Functions:**- Provides vast collection of Mathematical functions operations, it simplifies code and reduce need for manual implementation of complex algorithms.

## **Ans 2:-**
 **np.mean()**

**Functionality**:- Arithmetic average of elements along specified axis of array of the entire array if no axis

**Syntax**:- np.mean(a, axis = none, dtype = none, keepdims = False)

**Parameters**:- a, axis, dtype, out, keepdims

**When to use np.mean()**:-  When we need simple, unweight of array, when performance is crucial.

# **np.average()**

**Functionality**:- Computes the weighted average of elements along specified axis. Weight are not provided . Behaves like np.mean()

**Syntax**:- np.average(a, axis=None, weights=none, returned=False)

**Parameters**:- a, axis, weights, returned

**When to use np.average()**:- When we need weighted average and have varities for each elements.

## **Examples Below of np.mean() and np.average()**:-

In [1]:
#np.mean()
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(np.mean(arr))

3.5


In [3]:
#np.average()
import numpy as np
arr = np.array([[1,9,3],[4,5,8]])
print(np.average(arr))

5.0


# Ans 3:

**Methods for reversing a NumPy array along different axes**

Using Slicing([::-1]) :- It is a method to convenient way to reverse the elements of array. -1 indicates the step, and a negative step reverse the order.

# **Example Below for 1D Array and 2D Array:-**




In [4]:
# 1D

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[::-1])

[5 4 3 2 1]


In [5]:
# 2D

import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr[::-1])

[[4 5 6]
 [1 2 3]]


# Ans 4

## **Importance of Data Type:-**

a)Memory Managment

b)Performance

**Determine the Data Type of NumPy Array**


In [7]:
import numpy as np

#creating a NumPy array
arr = np.array([1, 2, 7, 8])

#checking the data type of elements in the array
print(arr.dtype)


int64


# Ans 5

**Key Features of ndarray in NumPy:**

a) **Homogeneous Data Typ**e:- It must be of same data type. For eg all integers, all floats, all strings.

b) **Multi-dimensional**:- It supports multiple dimensional like 1D, 2D, 3B and etc.

c) **Fixed Size**:- When ndarray is created then size cannot change.

d) **Efficient Memory Storage**:- ndarray stored in blocks of memory, leading efficicent access and manipulation. This is stored as arrays of ponters.

e) **Built-in Mathematical Functions**:- It provides a rich set which are optimized functions that optimized for operations, includes linear algebra, functions, random number.

**Standard Python Lists:**

a)**Data Type:-**

**ndarray**:- Hemogeneous.Every element must be same data type.

**Python Lists:-** Heterogenous.Contain elements of different data types.Eg are integers, strings, and floats in same list.

**b)Multi-Dimensional Spport:-**

**ndarray** :- Easily represents and manipulates multi-dimensional data.Eg are matrix, tensors

**Pyton Lists** :- Create nested lists to represent multi-dimensional data but they work with less efficient.

# Ans 6


**1. Memory Efficiency:-**

**Compact Storage**: NumPy arrays are stored in  blocks of memory, it leads to lower memory  compared to Python lists which store reference to objects. This creduces memory  significantly when dealing with large datasets.

**2. Data Type Homogeneity:-**

**Uniform Data Types:** NumPy arrays require elements to be of  same data type allowing for more efficient use of memory . In Python lists can hold mixed data types, leading due to type checking and management.

**3. Vectorized Operations**

**Element-wise Operations:** NumPy allows for vectorized operations, operations can be performed on entire arrays without the need for  loops in Python. This  low-level  and results in fast execution.

**4.** **Broadcasting:-**

Automatic Expansion: NumPy support broadcasting, it allows arrays of different shapes to use together in operations. This feature reduces the need for manually resizing arrays leads to cleaner and more code.

**5. Optimized Libraries**

Compiled Backend: NumPy is built on C and Fortran libraries like BLAS and LAPACK, which enhances performance for linear algebra operations and other numerical computations.

**6. Advanced Indexing and Slicing**

**Efficient Access:** NumPy  advanced indexing and slicing capability that is more efficient than Python list slicing, data manipulation and retrieval.

**7. Reduction of Python Overhead**

**Fewer Function Calls:** NumPy functions are in C, reducing the association with Python function calls. Operations on NumPy arrays execute much faster than operations performed on Python lists.

**8. Parallelization**

**Parallel Computing:** NumPy functions can  multi-threading and vectorized instructions, making that faster for big datasets. This parallel is often not achievable with standard Python lists.

**9. Extensive Functionality**

**Built-in Functions:** NumPy provides a  library of mathematical functions for performance, reducing t for users to implement solutions and allows more straightforward, efficient code.



# Ans 7

**vstack()** stacks vertical, increase in number of rows.

**hstack()** stacks horizontal, increase in number of columns.


**Examples Below of vstack() and hstack()**

In [8]:
import numpy as np

array1 = np.array([[1, 2, 3],[6, 8, 9]])
array2 = np.array([[4, 5, 6],[2, 5, 10]])

# Vertical
result_vertical = np.vstack((array1, array2))

print("result_vertical:")
print(result_vertical)

result_vertical:
[[ 1  2  3]
 [ 6  8  9]
 [ 4  5  6]
 [ 2  5 10]]


In [9]:
import numpy as np

array1 = np.array([[1, 2, 3],[6, 8, 9]])
array2 = np.array([[4, 5, 6],[2, 5, 10]])

# Horizontal
result_horizontal = np.hstack((array1, array2))

print("result_horizontal:")
print(result_horizontal)

result_horizontal:
[[ 1  2  3  4  5  6]
 [ 6  8  9  2  5 10]]


# Ans 8

## **fliplr()**

**Purpose:** Flips array are horizontally.

**Applicable Dimension:**  2D arrays (matrices).

**Behavior:** In each row of the array, the elements are reverse in order.

## **flipud()**

**Purpose:** Flips array are vertically.

**Applicable Dimension:** affects 2D arrays but it's been applied to higher-dimensional arrays, where it flip with first axis.

**Behavior:** In each column of the array, the elements are reverse in rows.



## Effects on Various Array Dimensions

**1**)**2D Arrays:**

fliplr() reverses the  elements in each row of order.

flipud() reverses the order of the rows.

2)1D Arrays:**

fliplr() behaves as same as flipud() for 1D arrays by flipping them to reverse order of elements.

**3)Higher-Dimensional Arrays:**

flipud() flips along with first axis, affects all dimensions.

fliplr() only works as the last axis of 2D sub-arrays.


# Ans 9

array_split() method in NumPy is versatile function used for spliting an array into multiple sub-arrays along a axis.

**Functionality of array_split()**

**Basic Usage:**  Primary purpose of array_split() to divide an array into a special number of small arrays (sub-arrays).

**Parameters:**

**ary:** The input array to be split.

It can be an integer or  1-D array of sorted integers.
If a integer is represent the number of equal parts for spliting the array into
 an array of integer in the exact  where the splits should occur.

**axis: **
The axis along  to split array then default is 0 the first axis.

# Handling Uneven Splits

 Size of the array is not perfectly divisible by any number of sections requested, array_split().

**Uneven Distribution:** If array cannot be split evenly some of resulting sub-arrays will have one more element than other.

# Ans 10

Vectorization and broadcasting are two key concepts in NumPy that greatly affect the efficiency of array operations.

**Vectorization:-** Vectorization is to process the convert operations that  typically be in a loop into single operation that  perform on entire arrays once.This is because of NumPy operations are added into C code which runs much fast than Python loops.

**Benefits:**

**Speed:** By avoiding Python for loops and leveraging low-level implementations, vectorized operations are faster.

**Code Simplicity:** Vectorization leads to cleaner are more readable code operations can be expressed in fewer lines.

** Broadcasting**:- It is strong mechanism which allows NumPy to work with arrays has  different shapes during arithmetic operations it enables automatic expansion of smaller arrays to match with the shape of larger arrays without copying data, it saves memory.

**Working Process**

**Dimension Alignment:** NumPy compare the shapes of the two arrays, if they are different, it tries to by "stretching" the smaller array along the dimensions that are missing.

## Contribution to Efficient Array Operations

**Memory Efficiency:** Broadcasting allows for operations on arrays of different shapes without creating largemarrays, it is particularly beneficial working with large datasets.

**Simplicity and Clarity:** Code becomes easy to understand. Vectorized operations and broadcasting it replace loop it construct with simple arithmetic expressions for making the code clearer.

**Reduced Computation Time:**  vectorization and broadcasting both minimize the need for explicit loops in Python, which is slow due to interpreter overhead.